# -*- coding: utf-8 -*-
"""Cópia de Semana 2 -  Exercício de apoio - Introdução a Ciencia de Dados - COM350.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j55oaxUvCfPSguBlKvPvYsZywe1gHBRX

##Disciplina - Introdução a Ciência de Dados - Univesp
##Exercícios de Apoio da Semana 2

###1 - Carregue as bibliotecas NumPy e Pandas
"""

import numpy as np
import pandas as pd

"""###2 - Crie um NDArray com os seguintes valores [1, 2.5, 7, -78, -0.9, 130, 25]"""

dados = np.array([1, 2.5, 7, -78, -0.9, 130, 25])

dados

"""###3 - Crie um NDArray com os valores de 0 a 10"""

dados2 = np.arange(11)

dados2

"""###4 – Crie um NDArray de dimensão 2x5 com valores 1"""

dados3 = np.random.rand(2,5)

dados3

"""###5 – Crie um NDArray com valores de 1 a 100, com intervalos de 3 em 3."""

dados4 = np.arange(1,101,3)

dados4

"""###6 – Mostre as raízes quadradas dos valores do NDArray criado no exercícios 5."""

sqrdados4 = np.sqrt(dados4)

sqrdados4

"""###7 – Altere a décima posição do NDArray criado no exercício 5 com o dobro do seu valor."""

dados4[10]

dados4[10] = dados4[10]*2

dados4

"""###8 – Execute o comando para criar um Dataframe com os dados disponíveis no notebook."""

dados={'Empresa':['Microsoft', 'Google','Univesp','NVData Analytics','Power Bi Experience','USP'], 'Qtde Func':[1000, 1500,500, 100,100,499], 'Site':['https://www.microsoft.com/pt-br','https://www.google.com/','https://univesp.br/','https://www.nvdata.com.br/','https://powerbiexperience.com/pt/','https://www.usp.br/'],'Instagram':['@microsoft','@google','@univespoficial','@nv_data','@leokarpa','@usp.oficial'],'Criação':[1975,1998,2012,2019,2016,1934], 'País':['EUA','EUA','Brasil','Brasil','Brasil','Brasil']}

dados_df = pd.DataFrame(dados)

"""###9 – Execute um comando que seja possível identificar qual a média da quantidade de funcionários que as empresas listadas tem. Informe também a soma dos funcionários que as empresas tem.

"""

dados['Qtde Func']

funcionarios = dados['Qtde Func']

mediafuncionarios = np.mean(funcionarios)

mediafuncionarios

somafuncionarios = np.sum(funcionarios)

somafuncionarios

"""###10 – Mostre as primeiras 3 linhas do dataframe."""

dados_df.head(3)

"""###11 – Mostre as últimas 3 linhas do dataframe."""

dados_df.tail(3)

"""###12 – Liste apenas as linhas em que as empresas foram criadas nos últimos 10 anos. Informe a quantidade de registros."""

last10 = dados_df[dados_df['Criação'] > 2010]
last10

"""###13 – Vamos imaginar que em todas as empresas exista 1 chefe para cada 23 funcionários. Crie uma coluna que mostre a quantidade de chefes que cada empresa teria e depois informe quantos chefes teríamos ao todo. (os valores não precisam ser números inteiros, é apenas uma estimativa).

"""

dados_df['Chefia'] = dados_df['Qtde Func']/23
dados_df